# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: beefy-balance-indexer
description: Beefy Finance Balance Indexer - Tracks ERC20 balances across multiple networks
unordered_multichain_mode: true
preload_handlers: false

contracts:
  # factories
  - name: ClassicVaultFactory
    abi_file_path: abis/beefy/classic/ClassicVaultFactory.json
    handler: src/EventHandlers.factory.ts
    events:
      - event: "ProxyCreated(address proxy)"
        name: VaultOrStrategyCreated
  - name: ClassicBoostFactory
    abi_file_path: abis/beefy/classic/ClassicBoostFactory.json
    handler: src/EventHandlers.factory.ts
    events:
      - event: "ProxyCreated(address proxy)"
        name: BoostCreated

  - name: RewardPoolFactory
    abi_file_path: abis/beefy/clm/RewardPoolFactory.json
    handler: src/EventHandlers.factory.ts
    events:
      - event: "ProxyCreated(address proxy)"
        name: RewardPoolCreated
  - name: CLMManagerFactory
    abi_file_path: abis/beefy/clm/CLMManagerFactory.json
    handler: src/EventHandlers.factory.ts
    events:
      - event: "ProxyCreated(address proxy)"
        name: CLMManagerCreated

  - name: ContractFactory
    abi_file_path: abis/beefy/ContractFactory.json
    handler: src/EventHandlers.factory.ts
    events:
      - event: "ContractDeployed(bytes32 rewardPoolName,address proxy)"

  # contracts
  - name: Token
    abi_file_path: abis/IERC20/IERC20.json
    handler: src/EventHandlers.token.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"

networks:
  - id: 8453 # base
    start_block: 2181945
    contracts:
      - name: ClassicVaultFactory
        address: 
          - 0xBC4a342B0c057501E081484A2d24e576E854F823
      - name: ClassicBoostFactory
        address: 
          - 0x9a313205f50e1192da6d71d1e32dad3487230c55

      - name: RewardPoolFactory
        address: 
          - 0x13F518Aa15CA3296E51CEAFB44A8D86660E97B3a
      - name: CLMManagerFactory
        address: 
          - 0x7bC78990AC1ef0754CFdE935B2D84E9acF13ed29

      - name: ContractFactory
        address: 
          - 0xcc536552A6214d6667fBC3EC38965F7f556A6391

      # individual products created without factory
      - name: Token # ClassicVault
        address: 
          - 0x62e5b9934dcb87618cfc74b222305d16c997e8c1
          - 0xc55E93C62874D8100dBd2DfE307EDc1036ad5434
